---
kind: pipeline
name: default-linux-arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: fossa-arm64
    image: rancher/dapper:v0.5.4
    environment:
      FOSSA_API_KEY:
        from_secret: FOSSA_API_KEY
    commands:
      - curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/spectrometer/master/install.sh | bash
      - fossa analyze
      - fossa test
    when:
      event:
        - pull_request