kind: pipeline
type: docker
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello world
  - echo update to trigger build
  when:
    event:
    - pull_request
    instance:
    - drone-pr.rancher.io
node:
  drone_lab: true
