kind: pipeline
type: docker
name: linux-amd64
node:
  drone_lab: true

platform:
  os: linux
  arch: amd64

steps:
- name: pr-introspection
  image: docker
  commands:
  - docker version
  - docker info
  - docker images
  - docker ps
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - pull_request
    instance:
    - drone-pr.rancher.io
- name: publish-introspection
  image: docker
  commands:
  - docker version
  - docker info
  - docker images
  - docker ps
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
      exclude:
      - pull_request
    instance:
    - drone-publish.rancher.io
volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: linux-arm64
node:
  drone_lab: true

platform:
  os: linux
  arch: arm64

steps:
- name: pr-introspection
  image: docker
  commands:
  - docker version
  - docker info
  - docker images
  - docker ps
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - pull_request
    instance:
    - drone-pr.rancher.io
- name: publish-introspection
  image: docker
  commands:
  - docker version
  - docker info
  - docker images
  - docker ps
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
      exclude:
      - pull_request
    instance:
    - drone-publish.rancher.io
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
---
kind: pipeline
type: docker
name: linux-arm
node:
  drone_lab: true

platform:
  os: linux
  arch: arm

steps:
- name: pr-introspection
  image: docker
  commands:
  - docker version
  - docker info
  - docker images
  - docker ps
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - pull_request
    instance:
    - drone-pr.rancher.io
- name: publish-introspection
  image: docker
  commands:
  - docker version
  - docker info
  - docker images
  - docker ps
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
      exclude:
      - pull_request
    instance:
    - drone-publish.rancher.io
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
---
kind: pipeline
type: docker
name: windows-1809
node:
  drone_lab: true

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: pr-introspection
  image: docker:windowsservercore-1809
  commands:
  - docker version
  - docker info
  - docker images
  - docker ps
  volumes:
  - name: docker
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - pull_request
    instance:
    - drone-pr.rancher.io
- name: publish-introspection
  image: docker:windowsservercore-1809
  commands:
  - docker version
  - docker info
  - docker images
  - docker ps
  volumes:
  - name: docker
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
      exclude:
      - pull_request
    instance:
    - drone-publish.rancher.io
volumes:
- name: docker
  host:
    path: \\\\.\\pipe\\docker_engine
---
kind: pipeline
type: docker
name: windows-2022
node:
  drone_lab: true

platform:
  os: windows
  arch: amd64
  version: 2022

clone:
  disable: true

steps:
- name: clone
  image: rancher/drone-images:git-amd64-ltsc2022

- name: pr-introspection
  image: docker:windowsservercore
  commands:
  - docker version
  - docker info
  - docker images
  - docker ps
  volumes:
  - name: docker
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - pull_request
    instance:
    - drone-pr.rancher.io
- name: publish-introspection
  image: docker:windowsservercore
  commands:
  - docker version
  - docker info
  - docker images
  - docker ps
  volumes:
  - name: docker
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
      exclude:
      - pull_request
    instance:
    - drone-publish.rancher.io
volumes:
- name: docker
  host:
    path: \\\\.\\pipe\\docker_engine
